export interface ClockTemplate {
  id: string;
  name: string;
  description: string;
  type: 'analog' | 'digital';
  previewBg: string;
  previewAccent: string;
}

export const ANALOG_TEMPLATES: ClockTemplate[] = [
  {
    id: 'classic',
    name: 'Classic Standard',
    description: 'Traditional white dial with crisp black numbers and red second hand.',
    type: 'analog',
    previewBg: 'bg-white',
    previewAccent: '#ff5252',
  },
  {
    id: 'railway',
    name: 'Swiss Railway (Sapling)',
    description: 'Rectangular railway tick marks with clean sans-serif dial and loop second hand.',
    type: 'analog',
    previewBg: 'bg-slate-50',
    previewAccent: '#d32f2f',
  },
  {
    id: 'dotted',
    name: 'Dotted Rim',
    description: 'Double outer rim with fine dotted minute track around dial.',
    type: 'analog',
    previewBg: 'bg-white',
    previewAccent: '#e53935',
  },
  {
    id: 'tactical',
    name: 'Luminous Tactical',
    description: 'Dark charcoal face with luminescent green hand accents and high-contrast ticks.',
    type: 'analog',
    previewBg: 'bg-slate-900',
    previewAccent: '#4ade80',
  },
  {
    id: 'nordic',
    name: 'Minimalist Nordic',
    description: 'Off-white cream bezel with ultra-clean modern typography.',
    type: 'analog',
    previewBg: 'bg-amber-50/40',
    previewAccent: '#334155',
  },
  {
    id: 'roman',
    name: 'Vintage Roman',
    description: 'Parchment dial with classic Roman numerals and spade hands.',
    type: 'analog',
    previewBg: 'bg-amber-100/50',
    previewAccent: '#b45309',
  },
  {
    id: 'neon',
    name: 'Cyber Neon',
    description: 'Futuristic black dial with glowing cyan and magenta neon accents.',
    type: 'analog',
    previewBg: 'bg-black',
    previewAccent: '#06b6d4',
  },
  {
    id: 'kids',
    name: 'Playful Colorful Kids',
    description: 'Vibrant rainbow colored numbers for easy time reading.',
    type: 'analog',
    previewBg: 'bg-slate-950',
    previewAccent: '#f59e0b',
  },
  {
    id: 'seiko-combo',
    name: 'Dual Dial + LCD Screen',
    description: 'Classic analog watch face with embedded digital calendar display window.',
    type: 'analog',
    previewBg: 'bg-slate-100',
    previewAccent: '#2563eb',
  },
  {
    id: 'military-24h',
    name: '24-Hour Military',
    description: 'Dual inner/outer ring showing 12-hour numbers and 24-hour military numbers.',
    type: 'analog',
    previewBg: 'bg-stone-100',
    previewAccent: '#dc2626',
  },
  {
    id: 'skeleton-metal',
    name: 'Industrial Metal Cutout',
    description: 'Heavy industrial black metal skeletal frame with metallic gold hands.',
    type: 'analog',
    previewBg: 'bg-zinc-950',
    previewAccent: '#eab308',
  },
  {
    id: 'dark-wall',
    name: 'Matte Black Wall',
    description: 'Sleek dark dial with high-contrast bright white numbers and hands.',
    type: 'analog',
    previewBg: 'bg-zinc-900',
    previewAccent: '#ffffff',
  },
  {
    id: 'wooden-rustic',
    name: 'Rustic Walnut Wood',
    description: 'Warm mahogany wood grain rim with vintage cream dial and dark hands.',
    type: 'analog',
    previewBg: 'bg-amber-950',
    previewAccent: '#fbbf24',
  },
];

export const DIGITAL_TEMPLATES: ClockTemplate[] = [
  {
    id: 'digital-led',
    name: '7-Segment LED',
    description: 'Classic retro green LED digital watch display on dark bezel.',
    type: 'digital',
    previewBg: 'bg-slate-950',
    previewAccent: '#22c55e',
  },
  {
    id: 'digital-modern',
    name: 'Modern Minimal Card',
    description: 'Oversized clean typography with seconds pill indicator.',
    type: 'digital',
    previewBg: 'bg-base-200',
    previewAccent: '#3b82f6',
  },
  {
    id: 'digital-cyber',
    name: 'Cyberpunk Neon',
    description: 'Futuristic dark glass display with cyan/magenta glow.',
    type: 'digital',
    previewBg: 'bg-slate-900',
    previewAccent: '#ec4899',
  },
  {
    id: 'digital-flip',
    name: 'Retro Flip Clock',
    description: 'Split-card flip clock design with mechanical card line.',
    type: 'digital',
    previewBg: 'bg-zinc-900',
    previewAccent: '#ffffff',
  },
  {
    id: 'digital-lcd',
    name: 'Classic LCD Watch',
    description: 'Vintage digital watch look with greenish-grey LCD screen.',
    type: 'digital',
    previewBg: 'bg-[#9ea88e]',
    previewAccent: '#1c1917',
  },
  {
    id: 'digital-glass',
    name: 'Frosted Glass',
    description: 'Translucent glassmorphic panel with soft gradient text.',
    type: 'digital',
    previewBg: 'bg-gradient-to-br from-indigo-900 to-slate-900',
    previewAccent: '#818cf8',
  },
  {
    id: 'digital-rgb',
    name: 'RGB Spectrum Rainbow',
    description: 'Vibrant rainbow color gradient LED digits on dark stand.',
    type: 'digital',
    previewBg: 'bg-slate-950',
    previewAccent: '#f43f5e',
  },
  {
    id: 'digital-weather',
    name: 'Atomic Weather Station',
    description: 'Full desk station with time, date, temperature (72°F) and humidity (45%).',
    type: 'digital',
    previewBg: 'bg-slate-900',
    previewAccent: '#38bdf8',
  },
  {
    id: 'digital-floating-3d',
    name: '3D Floating LED Digits',
    description: 'Bold cutout 3D illuminated white digits with soft wall glow.',
    type: 'digital',
    previewBg: 'bg-zinc-900',
    previewAccent: '#ffffff',
  },
  {
    id: 'digital-red-bedside',
    name: 'Bedside Red Alarm',
    description: 'Classic bedside nightstand alarm clock with deep red LED numbers.',
    type: 'digital',
    previewBg: 'bg-black',
    previewAccent: '#ef4444',
  },
  {
    id: 'digital-vfd-blue',
    name: 'VFD Vacuum Tube Glow',
    description: 'Retro futuristic cyan-blue glowing vacuum tube display.',
    type: 'digital',
    previewBg: 'bg-slate-950',
    previewAccent: '#38bdf8',
  },
  {
    id: 'digital-pastel',
    name: 'Mini Pastel Desk Clock',
    description: 'Cute rounded mint/pastel desk alarm clock with clear LCD digits.',
    type: 'digital',
    previewBg: 'bg-teal-100',
    previewAccent: '#0f766e',
  },
];
